### PR TITLE
Add open source enthousiast event

### PR DESCRIPTION
**Pull request by raatmarien**
The most dangerous (-ly boring) of them all

### CODE REVIEW

**Comment by m-rtijn** [comment]
Nice one marien!

**Comment by raatmarien** [comment]
WOooooOOOoooOOOooOOO

**Comment by jochem88** [comment]
*free software, open source enthusiasts would recommend MIT.

**Comment by raatmarien** [comment]
> You died, you were bored to death by the open source enthousiast.

:p

**Pull request merged**
